import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import '@fontsource-variable/reem-kufi-fun'; // Supports weights 400-700
import '@fontsource/londrina-solid/100.css';
import '@fontsource/londrina-solid/300.css';
import '@fontsource/londrina-solid/400.css';
import '@fontsource/londrina-solid/900.css';
import Footer from "@/components/footer";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "It's  a website ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" max-w-4xl mx-auto max-h-screen h-screen flex flex-col">
        <NavBar/>

        {children}
        
        <Footer/>
      </body>
    </html>
  );
}
